/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as RuntimesRouteImport } from './routes/runtimes'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as SkillsIdRouteImport } from './routes/skills.$id'
import { Route as RuntimesIndexRouteImport } from './routes/runtimes.index'
import { Route as RuntimesIdRouteImport } from './routes/runtimes.$id'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimesRoute = RuntimesRouteImport.update({
  id: '/runtimes',
  path: '/runtimes',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkillsRoute,
} as any)
const SkillsIdRoute = SkillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SkillsRoute,
} as any)
const RuntimesIndexRoute = RuntimesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RuntimesRoute,
} as any)
const RuntimesIdRoute = RuntimesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RuntimesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/runtimes': typeof RuntimesRouteWithChildren
  '/agents/$id': typeof AgentsIdRoute
  '/skills/': typeof SkillsIndexRoute
  '/skills/$id': typeof SkillsIdRoute
  '/runtimes/': typeof RuntimesIndexRoute
  '/runtimes/$id': typeof RuntimesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsIndexRoute
  '/runtimes': typeof RuntimesIndexRoute
  '/agents/$id': typeof AgentsIdRoute
  '/skills/$id': typeof SkillsIdRoute
  '/runtimes/$id': typeof RuntimesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/runtimes': typeof RuntimesRouteWithChildren
  '/agents/$id': typeof AgentsIdRoute
  '/skills/': typeof SkillsIndexRoute
  '/skills/$id': typeof SkillsIdRoute
  '/runtimes/': typeof RuntimesIndexRoute
  '/runtimes/$id': typeof RuntimesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/runs'
    | '/skills'
    | '/runtimes'
    | '/agents/$id'
    | '/skills/'
    | '/skills/$id'
    | '/runtimes/'
    | '/runtimes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/runs'
    | '/skills'
    | '/runtimes'
    | '/agents/$id'
    | '/skills/$id'
    | '/runtimes/$id'
  id:
    | '__root__'
    | '/'
    | '/runs'
    | '/skills'
    | '/runtimes'
    | '/agents/$id'
    | '/skills/'
    | '/skills/$id'
    | '/runtimes/'
    | '/runtimes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunsRoute: typeof RunsRoute
  SkillsRoute: typeof SkillsRouteWithChildren
  RuntimesRoute: typeof RuntimesRouteWithChildren
  AgentsIdRoute: typeof AgentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtimes': {
      id: '/runtimes'
      path: '/runtimes'
      fullPath: '/runtimes'
      preLoaderRoute: typeof RuntimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/skills/$id': {
      id: '/skills/$id'
      path: '/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof SkillsIdRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/runtimes/': {
      id: '/runtimes/'
      path: '/'
      fullPath: '/runtimes/'
      preLoaderRoute: typeof RuntimesIndexRouteImport
      parentRoute: typeof RuntimesRoute
    }
    '/runtimes/$id': {
      id: '/runtimes/$id'
      path: '/$id'
      fullPath: '/runtimes/$id'
      preLoaderRoute: typeof RuntimesIdRouteImport
      parentRoute: typeof RuntimesRoute
    }
  }
}

interface SkillsRouteChildren {
  SkillsIndexRoute: typeof SkillsIndexRoute
  SkillsIdRoute: typeof SkillsIdRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsIndexRoute: SkillsIndexRoute,
  SkillsIdRoute: SkillsIdRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

interface RuntimesRouteChildren {
  RuntimesIndexRoute: typeof RuntimesIndexRoute
  RuntimesIdRoute: typeof RuntimesIdRoute
}

const RuntimesRouteChildren: RuntimesRouteChildren = {
  RuntimesIndexRoute: RuntimesIndexRoute,
  RuntimesIdRoute: RuntimesIdRoute,
}

const RuntimesRouteWithChildren =
  RuntimesRoute._addFileChildren(RuntimesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRoute: RunsRoute,
  SkillsRoute: SkillsRouteWithChildren,
  RuntimesRoute: RuntimesRouteWithChildren,
  AgentsIdRoute: AgentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
