/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as SkillsIdRouteImport } from './routes/skills.$id'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIdRoute = SkillsIdRouteImport.update({
  id: '/skills/$id',
  path: '/skills/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/skills/$id': typeof SkillsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/skills/$id': typeof SkillsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/runs': typeof RunsRoute
  '/skills': typeof SkillsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/skills/$id': typeof SkillsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/runs' | '/skills' | '/agents/$id' | '/skills/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/runs' | '/skills' | '/agents/$id' | '/skills/$id'
  id: '__root__' | '/' | '/runs' | '/skills' | '/agents/$id' | '/skills/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunsRoute: typeof RunsRoute
  SkillsRoute: typeof SkillsRoute
  AgentsIdRoute: typeof AgentsIdRoute
  SkillsIdRoute: typeof SkillsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$id': {
      id: '/skills/$id'
      path: '/skills/$id'
      fullPath: '/skills/$id'
      preLoaderRoute: typeof SkillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRoute: RunsRoute,
  SkillsRoute: SkillsRoute,
  AgentsIdRoute: AgentsIdRoute,
  SkillsIdRoute: SkillsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
